Faq component
EnCiv/undebate-ssp pull request #121
Opened 2022-03-14 18:15 UTC by gitgood-ENT

2022-03-15 18:06 UTC, ddfridley requested changes
@gitgood-ENT great start, and your code works! Please see the line by line comments.  I explained about animating the height, but that's extra credit.

2022-03-15 18:06 UTC, ddfridley commented on stories/frequently-asked-questions.stories.js
> +FrequentlyAskedQuestionsTest.args = {}
To pass the faq as a property to the FAQ component
```
FrequentlyAskedQuestionsTest.args = {faq}
```
Please also create test cases for {faq: []} and {faq: undefined} and make sure the component under test doesn't blow up in either of those cases
 example:
```
export const Empty = Template.bind({})
Empty.args = {}

export const ZeroLength = Template.bind({})
ZeroLength.args = {faq: []}
```

2022-03-17 22:55 UTC, gitgood-ENT commented
All issues resolved, let me know if there are any other changes or questions. Still need to import the have a question component to the bottom once that is completed.

2022-03-18 22:20 UTC, ddfridley requested changes
I figure we should just go all in with the height animation. 

I've put in the code for an Opener Component.  It's a common practice to create components to use in other components.  This solves the height problem in a generic way.

2022-03-23 18:55 UTC, gitgood-ENT commented
@ddfridley please review changes

2022-03-24 20:01 UTC, ddfridley requested changes
Noah - this all look great. The opener looks smooth.  There's just one thing I didn't notice until now.  We need to change the cursor to a pointer when someone hovers over the question of the ^

Look at question.js to see how to do hover in the styles.

Sorry to keep dragging this out - but it's educational right?

2022-03-28 17:45 UTC, ddfridley approved these changes
done.  Thanks!

2022-03-28 17:45 UTC, merged