Sign insign up 108
EnCiv/undebate-ssp pull request #129
Opened 2022-03-27 18:31 UTC by Gluay88

2022-03-28 17:51 UTC, ddfridley commented on stories/signin-signup.stories.js
> +//https://github.com/EnCiv/undebate-ssp/issues/108
this story is the same as sign-in-button.stories.js can you remove one of them.

2022-03-28 18:16 UTC, ddfridley requested changes
I've left comments in several files that need to be removed from the branch.
The .DS_Store files need to be removed as well.  I think this code will do it.
```
rm app/.DS_Store
rm .DS_Store
git rm --cached .DS_Store
git rm --cached app/.DS_Store
echo .DS_Store >> .gitignore
git add .
git commit -m "removed .DS_Store"
```
you will also need to 
```
rm package-lock.json
git checkout package-lock.json
```
To revert it back after you revert back package.json
Changes in package-lock are really hard to merge.

2022-03-28 18:16 UTC, ddfridley commented on app/components/log-in.js
> +////https://github.com/EnCiv/undebate-ssp/issues/108
I don't see this file being used anywhere - if not then remove it. Otherwise lets discuss it seems to be alot like the signin-signup file.

2022-03-28 20:22 UTC, Gluay88 commented
Done. Thank you

2022-03-28 20:43 UTC, ddfridley requested changes
see the line by line comments, plus you need to remove package-lock.json and git checkout package-lock.json

2022-03-28 20:43 UTC, ddfridley commented on .gitignore
> +globalConfig.json.DS_Store
please edit the .gitignore file and put a new-line between globalConfig.json and .DS_Store 
And then put a new line after the .DS_Store

2022-03-28 20:43 UTC, ddfridley commented on stories/sign-in-button.stories.js
> +import React from 'react'
I think this file is the same as stories/signin-signup.stories.js  and this one should be removed.

2022-04-05 20:24 UTC, ddfridley requested changes
I think I dropped the ball on this one.  It seems to be working great, but here are some changes. Perhaps some we've already talked about.

- [ ] From the story, When I run the Log In function, I get this error in the browser console:

```
use-auth.js:183 Uncaught ReferenceError: logger is not defined
    at use-auth.js:183:1
    at Request.callback (client.js:647:1)
    at Request.<anonymous> (client.js:465:1)
    at Request.Emitter.emit (index.js:145:1)
    at XMLHttpRequest.xhr.onreadystatechange (client.js:763:1)
```
global.logger needs to be defined in template of the story:
```
if(typeof global.logger==='undefined') global.logger=console
```

- [ ] Also, the useEffect code from [useAuth.stories.js](https://github.com/EnCiv/civil-client/blob/main/stories/use-auth.stories.js) needs to be added to the component so things like reset password will work.
- [ ] We need to have add a prop called tab. (I'm open to a better name)
if tab==="signup" then then signup tab will be shown.  tab===="login" then the Log In tab will be shown.  Anything else defaults to signup. We need this so that buttons that bring up this popup can control where to start.
- [ ] When a tab is selected, that tabs name (at the top) will be in the highlight color (goldish).
- [ ] On the signup page, the "I agree to ..." button and link should be moved above the Sign Up button - so the use does things in top down order.
- [ ] Send Reset Password should only be shown on the login tab
- [ ] remove your package-lock.json file and then git checkout package-lock.json so that you aren't trying to checking a file.
- [ ] after doing the package-lock stuff, merge with main.  There will be conflicts on .gitignore and on iotas.json.  For .gitignore just use what's in main.  for iotas you will have to merge so your new iota is there and whatever other changes. - let me know if you have trouble with this.

2022-04-11 18:42 UTC, ddfridley commented
@Gluay88 there is a new way to do stories. See the pattern in stories/election-heater.storis.js  you can use this instead.  If you do, then you don't have to worry about logger, or the useEffect Code from useAuth.stories.js - they are already in stories/make-chapter.js. I'm hoping the new pattern is easier to use - but let me know what you think.

2022-05-26 21:08 UTC, merged